- hosts: localhost
  connection: localhost
  gather_facts: False

  tasks:
    - name: create an instance
      ec2:
         key_name: my_key
         instance_type: t2.micro
         image: ami-0eb89db7593b5d434
         region: eu-west-2
         wait: true
         exact_count: 2
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: ec2hosts
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

- hosts: ec2hosts
  remote_user: ubuntu
  gather_facts: false
  become: yes

  tasks:
    - name: update sources and install nginx
      apt:
        name: nginx
        update_cache: yes

    - name: move nginx configs to sites-available
      copy:
        src: roles/common/copy/proxy.conf
        dest: /etc/nginx/sites-available/proxy.conf

    - name: delete default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: link new config to sites-enabled
      file:
        src: /etc/nginx/sites-available/proxy.conf
        dest: /etc/nginx/sites-enabled/proxy.conf
        state: link
      notify:
      - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
